name: Create Test Environment

on:
  pull_request:
    branches:
      - master

jobs:
  create-infra:
    name: Setup Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure/pr-module
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-west-1'
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-env name=BRANCH_NAME::${{ github.head_ref }}"
      - run: terraform init
      - run: terraform workspace select $BRANCH_NAME || terraform workspace new $BRANCH_NAME
      - run: terraform apply -var="branch_name=$BRANCH_NAME" -auto-approve
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
